name: Staging - Theme Shopify deploy to Staging - Single Store
on:
  push:
    tags:
      - 'v*'
      
concurrency: 
  group: staging_environment_theme
  cancel-in-progress: true
  
jobs:
 deploy-shopify-theme:
    name: Staging - Theme Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Production - Theme Deploy live theme
        uses: Shopfabrik-Berlin/shopify-actions@shopify-2.0
        env:
          TASK: DEPLOY
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PRODUCTION_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_PRODUCTION_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_PRODUCTION_THEME_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
