name: Preview - Delete Shopify Theme Test

on:
  pull_request:
      types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
    - name: Delete preview theme
      uses: Shopfabrik-Berlin/shopify-actions@shopify-2.0
      env:
        TASK: PREVIEW_DELETE
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
