name: Stage - Deploy Theme Shopify Test
on:
  push:
    branches:
      - development
      
concurrency: 
  group: staging_environment_theme
  cancel-in-progress: true
  
jobs:
 deploy-shopify-theme:
    name: Staging - Theme Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development

      # ... steps to build Shopify theme ...

      - name: Staging - Deploy staging theme
        uses: Shopfabrik-Berlin/shopify-actions@shopify-2.0
        env:
          TASK: DEPLOY
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID_STAGE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
