name: Preview - Deploy Shopify Theme Test

on:
  pull_request:
      types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    # ... steps to build Shopify theme ...

    - name: Deploy preview theme
      uses: Shopfabrik-Berlin/shopify-actions@shopify-2.0
      env:
        TASK: PREVIEW
        SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASANA_TOKEN: ${{ secrets.ASANA_TOKEN }}
        ASANA_PR_PROJECT_ID: ${{ secrets.ASANA_PR_PROJECT_ID }}
        ASANA_PR_ASSIGNEE: ${{ secrets.ASANA_PR_ASSIGNEE }}
        SHOPIFY_THEME_DIR_PATH: test/theme
