name: Production - Backup Theme Shopify Test
on:
  schedule:
    - cron: "0 9 * * *"
  
jobs:
 backup-shopify-theme:
    name: Production - Backup Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: backup
      - name: Backup theme
        uses: Shopfabrik-Berlin/shopify-actions@shopify-2.0
        env:
          TASK: BACKUP
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PRODUCTION_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_PRODUCTION_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_PRODUCTION_THEME_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for untracked && push
        run: |
          if [[ -n $(git status --porcelain) ]];
            then
              echo "$(date) => Automated Backup Generated \n" >> backup.log
              git config --local user.email "backup_engine@github.com"
              git config --local user.name "Backup Engine"
              git add .
              git commit -m "Daily Backup Action"
              git push;
          fi
