name: Delete Shopify Theme Review Test

on:
  pull_request:
      types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: yarn install      
    - name: Deploy preview theme
      uses: Shopfabrik-Berlin/shopify-actions@shopify-2.0
      env:
        TASK: PREVIEW
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASANA_TOKEN: ${{ secrets.ASANA_TOKEN }}
        ASANA_PR_PROJECT_ID: ${{ secrets.ASANA_PR_PROJECT_ID }}